# Generated by Django 3.2.9 on 2021-11-29 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={},
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='object_buy_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return', to='magazine.objectbuyproduct'),
        ),
    ]
