# Generated by Django 3.2.9 on 2021-11-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20211129_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='object_buy_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_return', to='magazine.objectbuyproduct'),
        ),
    ]
